// import Head from "next/head";
// import Image from "next/image";
// import Link from "next/link";
// import styles from "../styles/Home.module.css";

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>
//         <Link href={"/login"}>Sign In</Link>
//       </main>
//     </div>
//   );
// }

import { Session } from "next-auth";
import { getSession, useSession } from "next-auth/react";
import Link from "next/link";
import { SessionProps } from "../types/SessionProps";
import AvatarButton from "../components/AvatarButton";

const Home = ({ session }: SessionProps) => {
  // const { data: session } = useSession();
  console.log(session);
  const CurentPage = session ? <UserPage session={session} /> : <GuestPage />;

  return (
    <div>
      {/* Navbar */}
      <nav className="bg-gray-800 p-4 text-white fixed top-0 left-0 w-full flex justify-between items-center">
        <div className="text-lg font-bold ml-4">Navbar</div>
        <div className="flex items-center">
          <div className="mr-4">
            {/* Search box */}
            <input
              type="text"
              placeholder="Search"
              className="border rounded-md px-2 py-1 text-black"
            />
          </div>
          <div className="mr-4">
            {/* Function 1 */}
            <button>Function 1</button>
          </div>
          <div className="mr-4">
            {/* Function 2 */}
            <button>Function 2</button>
          </div>
          <div className="mr-4">
            {/* Function 3 */}
            <button>Function 3</button>
          </div>
          {session ? (
            <div className="mr-4">
              {/* account function */}

              <AvatarButton/>
            </div>
          ) : (
            <></>
          )}
        </div>
      </nav>

      {/* Content */}
      <div className="bg-gradient-to-r from-blue-400 to-purple-500 min-h-screen flex items-center justify-center">
        {CurentPage}
      </div>
    </div>
  );
};

const GuestPage = () => (
  <Link
    href="/login"
    className="text-lg bg-indigo-600 text-white py-2 px-4 rounded-md"
  >
    Sign In / Sign Up
  </Link>
);

const UserPage = ({ session }: SessionProps) => (
  <div
    className="p-8 rounded-lg bg-white shadow-md w-fit max-w-fit"
    style={{ width: "fit-content" }}
  >
    <h1
      className="text-3xl font-bold mb-4"
      style={{ display: "table", tableLayout: "auto" }}
    >
      Welcome {session?.user?.name ?? ""} to Our Website
    </h1>
    <p className="text-gray-600 mb-6">
      Thank you for visiting. We are excited to have you here!
    </p>
  </div>
);

export default Home;


export async function getServerSideProps({ req }: any) {
  const session = await getSession({ req });
  return {
    props: {
      session,
    },
  };
}
